### PR TITLE
Implement basic check.bin parser.

### PR DESCRIPTION
**Pull request by RoadTrain**

### CODE REVIEW

**Comment by DavoSK** [comment]
@RoadTrain can you add also links parsing, thanks

**Comment by drummyfish** [comment]
Hello, thank you for your contribution, you picked up the coding style pretty easily, very nice. @DavoSK was working on check.bin, so I guess you'll be able to put your work together.

If you want to discuss a work in progress, e.g. the possible link parsing etc., make a pull request and put [DON'T MERGE] in the title, that way others can see what you're working on and give you a feedback. Also we'll probably make a discord or something soon, where you can join us if you plan further contributions. Happy coding.

**Comment by RoadTrain** [comment]
@DavoSK Oh, I see you have also writtent a format utility and an OSG implementation. Would be cool to merge it. As for links parsing, I'm not there yet, so if you have any ideas, feel free to share.

**Comment by drummyfish** [comment]
@RoadTrain we have since started a discord server where you can discuss with us if you want. You'll find the link in our README.

**Pull request merged**
