### PR TITLE
Implement .6ds parsing

### PR DESCRIPTION
**Pull request by RoadTrain**
6ds contain shadow models for corresponding 4ds models.

### CODE REVIEW

**Comment by drummyfish** [comment]
`/home/tastyfish/Git/OpenMF/components/6ds/parser.cpp:11:26: error: ISO C++ forbids comparison between pointer and integer [-fpermissive]`

Should use strcmp or something.

**Comment by RoadTrain** [comment]
Oh, hell, didn't check that after adding. Thanks for noticing. Gonna submit fix soon.

**Comment by RoadTrain** [comment]
@drummyfish Could you check once more please? I don't have a compiler at hand atm.

**Comment by RoadTrain** [comment]
I have fixed the compilation errors. The reason was using single quites instead of double. Errm.

**Comment by drummyfish** [comment]
Have you tested it? I'm really not sure about this comparison, it wouldn't work in C, not sure about Cpp, I can't see the operator overloaded in the string docs. I'd rather be safe and use the compare method.

**Comment by RoadTrain** [comment]
Yes, I have, seems to work fine.
6ds

**Pull request merged**
